### ISSUE TITLE
packet: create migration FAQ for users coming from raw

### ISSUE THREAD

**Issue by mdlayher** [mdlayher/packet#1]
I've already run into a couple of subtle situations while migrating other packages, and it'd be good to document these.

In particular, it's easy for calling code to forget to change `raw.Addr` to `packet.Addr` since the `net.PacketConn` methods take `net.Addr` and both types comply with it, but will subtly break with EINVAL if the wrong one is passed.

**Comment by gaby** [comment]
@mdlayher Where is the FAQ for this?

**Comment by gaby** [comment]
I was using `raw.ListenPacket` but it seems that func is not in this new package. The `packet.Listen` uses completely different arguments

**Comment by mdlayher** [comment]
There has been no need to create a FAQ in the year since I archived the old package.

Could you please open a new issue with information about what you are trying to do. Thanks.
