### ISSUE TITLE
Test_htons fails to build on big-endian hosts

### ISSUE THREAD

**Issue by dswarbrick** [mdlayher/packet#3]
Test_htons fails to build on big-endian hosts with an invalid operation.
```
# github.com/mdlayher/packet [github.com/mdlayher/packet.test]
src/github.com/mdlayher/packet/packet_internal_test.go:63:24: invalid operation: native.Endian == binary.LittleEndian (mismatched types binary.bigEndian and binary.littleEndian)
FAIL	github.com/mdlayher/packet [build failed]
```
This is because, on big-endian hosts, native.Endian will be binary.BigEndian.

binary.BigEndian and binary.LittleEndian are different _types_, and thus cannot be directly compared.

**Comment by dswarbrick** [comment]
Whilst looking at the tests, I also stumbled across these unusual tests:
```go
        {   
            name: "negative",
            i:    -1, 
        },  
        {   
            name: "too large",
            i:    math.MaxUint16 + 1,
        },
```
Why not make the htons function closer to its POSIX namesake, e.g. accept a uint16, which would make such tests redundant?

**Comment by mdlayher** [comment]
Fixed in https://github.com/mdlayher/packet/commit/153f88bd9f7fd66ad597a673a76aebb00f404a53. And I'm not interested in changing htons because the exported API accepts int.
